positive = ['acaibowls', 'afghani', 'african','arabian', 'arcades', 'argentine',
    'armenian',  'asianfusion', 'australian', 'austrian', 'bagels', 'bakeries',
    'bangladeshi',  'barcrawl', 'bars', 'bartenders', 'basque', 'bbq', 'belgian',  
    'brasseries', 'brazilian', 'breakfast_brunch', 'breweries', 'brewingsupplies',
    'bridal', 'british', 'bubbletea', 'buffets', 'burgers', 'burmese', 'butcher',
    'cabaret', 'cafes', 'cafeteria', 'cajun', 'cambodian', 'cantonese', 'caribbean', 
    'catering',  'cheese', 'cheesesteaks', 'chicken_wings', 'chickenshop', 'chinese', 
    'chocolate',  'colombian', 'comfortfood', 'creperies', 'cuban', 'culturalcenter',  
    'czech''delis', 'desserts', 'dimsum', 'diners', 'dinnertheater', 'distilleries','diyfood', 
    'dominican', 'donuts',  'egyptian', 'empanadas', 'eritrean', 'ethiopian', 'falafel', 'farmersmarket', 
    'festivals', 'filipino', 'fishnchips',  'fondue', 'food', 'food_court', 'fooddeliveryservices', 'foodstands', 
    'foodtrucks', 'french', 'galleries', 'gamemeat', 'gastropubs', 'gaybars', 'gelato', 'georgian', 'german',  
    'gluten_free', 'golf', 'golflessons', 'gourmet', 'greek', 'hainan', 'haitian', 'halal', 'hawaiian', 'hennaartists',
    'herbsandspices', 'himalayan', 'hkcafe', 'honduran', 'hookah_bars', 'hotdog', 'hotdogs',  'hotpot', 'iberian',  'importedfood', 
    'indonesian', 'indpak', 'internetcafe', 'intlgrocery', 'irish', 'irish_pubs', 'italian', 'izakaya', 'japacurry', 'japanese', 
    'jazzandblues', 'karaoke', 'kebab',  'kitchensupplies', 'korean', 'kosher',  'laotian', 'latin', 'laundromat', 'lebanese', 
    'localflavor', 'macarons', 'mags', 'malaysian',  'meats', 'mediterranean', 'mexican', 'mideastern', 'modern_european', 
    'mongolian', 'moroccan',  'newamerican', 'newmexican',   'noodles',  'organic_stores', 'pakistani', 'panasian', 
    'partyequipmentrentals', 'pastashops', 'persian', 'personalchefs', 'peruvian', 'petadoption', 'petstore', 'piadina', 
    'pianobars', 'pizza', 'playgrounds', 'poke', 'polish', 'poolhalls', 'popuprestaurants', 'portuguese', 'poutineries', 'pretzels', 
    'privatejetcharter', 'pubs', 'puertorican', 'ramen', 'raw_food', 'restaurants', 'russian', 'salad', 'salvadoran', 'sandwiches', 
    'sardinian', 'scandinavian', 'scottish', 'seafood', 'seafoodmarkets', 'senegalese', 'servicestations', 'shanghainese', 
    'sharedofficespaces', 'shavedice', 'sicilian', 'singaporean', 'slovakian', 'smokehouse','somali', 'soulfood', 'soup', 
    'southafrican', 'southern', 'spanish', 'speakeasies',  'srilankan', 'steak',   'sushi', 'syrian', 'szechuan', 'tacos', 
    'taiwanese', 'tapas', 'tapasmallplates',  'tea', 'teppanyaki', 'tex-mex', 'thai','themedcafes', 'tikibars', 'tobaccoshops', 
    'tradamerican', 'trinidadian', 'turkish', 'tuscan', 'uzbek', 
    'vegan', 'vegetarian', 'venezuelan',  'vietnamese', 'waffles', 'wine_bars', 'wraps']